-- This file is part of SA MoonLoader package.
-- Licensed under the MIT License.
-- Copyright (c) 2016, BlastHack Team <blast.hk>


local weapons = {
	FIST = 0,
	BRASSKNUCKLES = 1,
	GOLFCLUB = 2,
	NIGHTSTICK = 3,
	KNIFE = 4,
	BASEBALLBAT = 5,
	SHOVEL = 6,
	POOLCUE = 7,
	KATANA = 8,
	CHAINSAW = 9,
	PURPLEDILDO = 10,
	WHITEDILDO = 11,
	WHITEVIBRATOR = 12,
	SILVERVIBRATOR = 13,
	FLOWERS = 14,
	CANE = 15,
	GRENADE = 16,
	TEARGAS = 17,
	MOLOTOV = 18,
	COLT45 = 22,
	SILENCED = 23,
	DESERTEAGLE = 24,
	SHOTGUN = 25,
	SAWNOFFSHOTGUN = 26,
	COMBATSHOTGUN = 27,
	UZI = 28,
	MP5 = 29,
	AK47 = 30,
	M4 = 31,
	TEC9 = 32,
	RIFLE = 33,
	SNIPERRIFLE = 34,
	ROCKETLAUNCHER = 35,
	HEATSEEKER = 36,
	FLAMETHROWER = 37,
	MINIGUN = 38,
	SATCHELCHARGE = 39,
	DETONATOR = 40,
	SPRAYCAN = 41,
	FIREEXTINGUISHER = 42,
	CAMERA = 43,
	NIGHTVISION = 44,
	THERMALVISION = 45,
	PARACHUTE = 46
}

local id = weapons
weapons.names = {
	[id.FIST] = 'Fist',
	[id.BRASSKNUCKLES] = 'Brass Knuckles',
	[id.GOLFCLUB] = 'Клюшка',
	[id.NIGHTSTICK] = 'Дубинка',
	[id.KNIFE] = 'Нож',
	[id.BASEBALLBAT] = 'Бита',
	[id.SHOVEL] = 'Лопата',
	[id.POOLCUE] = 'Кий',
	[id.KATANA] = 'Катана',
	[id.CHAINSAW] = 'Пила',
	[id.PURPLEDILDO] = 'Фиолетовый дилдо',
	[id.WHITEDILDO] = 'Дилдо',
	[id.WHITEVIBRATOR] = 'Вибратор',
	[id.SILVERVIBRATOR] = 'Вибратор',
	[id.FLOWERS] = 'Цветы',
	[id.CANE] = 'Трость',
	[id.GRENADE] = 'Граната',
	[id.TEARGAS] = 'Газ. граната',
	[id.MOLOTOV] = 'Молотов',
	[id.COLT45] = 'Кольт 9mm',
	[id.SILENCED] = 'Тэйзер',
	[id.DESERTEAGLE] = 'Пустынный орёл',
	[id.SHOTGUN] = 'Дробовик',
	[id.SAWNOFFSHOTGUN] = 'Обрез',
	[id.COMBATSHOTGUN] = 'Дробовик',
	[id.UZI] = 'Узи',
	[id.MP5] = 'SMG',
	[id.AK47] = 'AK-47',
	[id.M4] = 'M4A1',
	[id.TEC9] = 'ТЕК-9',
	[id.RIFLE] = 'Ружьё',
	[id.SNIPERRIFLE] = 'Винтовка',
	[id.ROCKETLAUNCHER] = 'РПГ',
	[id.HEATSEEKER] = 'Самонаводящееся РПГ',
	[id.FLAMETHROWER] = 'Огнемёт',
	[id.MINIGUN] = 'Миниган',
	[id.SATCHELCHARGE] = 'Бомба',
	[id.DETONATOR] = 'Детонатор',
	[id.SPRAYCAN] = 'Болончик',
	[id.FIREEXTINGUISHER] = 'Огнетушитель',
	[id.CAMERA] = 'Камера',
	[id.NIGHTVISION] = 'ПНВ',
	[id.THERMALVISION] = 'Тепловизор',
	[id.PARACHUTE] = 'Парашют'
}

function weapons.get_name(id)
	return weapons.names[id]
end

return weapons
